include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    # Error Rules
    avoid_print: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style Rules
    camel_case_types: true
    camel_case_extensions: true
    file_names: true
    package_names: true
    library_names: true
    depend_on_referenced_packages: true

    # Coding Standards
    always_declare_return_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_rethrow_when_possible: true
    valid_regexps: true
