import 'package:scraki/features/video_poster/data/services/batch_video/models/batch_video_models.dart';
import 'package:scraki/features/video_poster/domain/entities/batch_video_config.dart';

class CompositionPlan {
  final int outputIndex;
  final List<String> segmentPaths;
  final List<double> segmentDurations;
  final String outputDir;
  final String tempDir;
  final BatchVideoConfig config;
  final String? ambientAudioPath;
  
  // Random parameters generated by Pipeline
  final CompositionParams params;
  
  // Input tracking
  final List<String> textOverlayPaths;
  final bool hasCustomAudio;
  final bool hasAmbientAudio;

  CompositionPlan({
    required this.outputIndex,
    required this.segmentPaths,
    required this.segmentDurations,
    required this.outputDir,
    required this.tempDir,
    required this.config,
    required this.params,
    this.ambientAudioPath,
    required this.textOverlayPaths,
    required this.hasCustomAudio,
    required this.hasAmbientAudio,
  });

  String get finalOutputPath => 
      '$outputDir/tik_final_${outputIndex.toString().padLeft(3, '0')}.mp4';
}

class CompositionParams {
  final int targetDuration;
  final double pts;
  final double brightness;
  final double contrast;
  final int gopSize;
  final int bFrames;
  final String creationTime;
  final AudioSpoofProfile audioProfile;
  final double hueShift;
  final double satFactor;
  final double vignetteAngle;
  final double zoomVal;
  final double cropJitterX;
  final double cropJitterY;
  final double panStartX;
  final double panStartY;
  final double panEndX;
  final double panEndY;
  final double transitionDuration;
  final String? lutFilePath;
  final double? gammaR;
  final double? gammaG;
  final double? gammaB;

  CompositionParams({
    required this.targetDuration,
    required this.pts,
    required this.brightness,
    required this.contrast,
    required this.gopSize,
    required this.bFrames,
    required this.creationTime,
    required this.audioProfile,
    required this.hueShift,
    required this.satFactor,
    required this.vignetteAngle,
    required this.zoomVal,
    required this.cropJitterX,
    required this.cropJitterY,
    required this.panStartX,
    required this.panStartY,
    required this.panEndX,
    required this.panEndY,
    required this.transitionDuration,
    this.lutFilePath,
    this.gammaR,
    this.gammaG,
    this.gammaB,
  });
}
