import 'package:freezed_annotation/freezed_annotation.dart';

part 'scrcpy_options.freezed.dart';

@freezed
class ScrcpyOptions with _$ScrcpyOptions {
  const factory ScrcpyOptions({
    @Default(0) int maxSize, // 0 means no limit
    @Default(8000000) int bitRate, // 8Mbps
    @Default(60) int maxFps,
    @Default(false) bool stayAwake,
    @Default('h265') String videoCodec,
    String? audioCodec,
    String? videoSource,
    String? audioSource,
    String? cameraFacing,
    String? crop,
    String? portRange,
    String? tunnelHost,
    int? tunnelPort,
    int? audioBitRate,
    int? angle,
    int? screenOffTimeout,
    String? captureOrientation,
    bool? captureOrientationLock,
    @Default(true) bool control,
    int? displayId,
    String? newDisplay,
    int? displayImePolicy,
    @Default(true) bool video,
    @Default(false) bool audio,
    bool? audioDup,
    bool? showTouches,
    String? videoCodecOptions,
    String? audioCodecOptions,
    String? videoEncoder,
    String? audioEncoder,
    String? cameraId,
    String? cameraSize,
    String? cameraAr,
    int? cameraFps,
    bool? forceAdbForward,
    bool? powerOffOnClose,
    @Default(true) bool clipboardAutosync,
    bool? downsizeOnError,
    bool? tcpip,
    String? tcpipDst,
    @Default(false) bool cleanup,
    bool? powerOn,
    bool? killAdbOnClose,
    bool? cameraHighSpeed,
    bool? vdDestroyContent,
    bool? vdSystemDecorations,
    bool? list,
    String? logLevel,
  }) = _ScrcpyOptions;
}

extension ScrcpyOptionsX on ScrcpyOptions {
  List<String> toArgs(String serverVersion, String scid) {
    return [
      serverVersion,
      'scid=$scid',
      if (logLevel != null) 'log_level=$logLevel' else 'log_level=info',
      'video_codec=$videoCodec',
      if (audioCodec != null) 'audio_codec=$audioCodec',
      if (videoSource != null) 'video_source=$videoSource',
      if (audioSource != null) 'audio_source=$audioSource',
      if (cameraFacing != null) 'camera_facing=$cameraFacing',
      if (crop != null) 'crop=$crop',
      if (portRange != null) 'port_range=$portRange',
      if (tunnelHost != null) 'tunnel_host=$tunnelHost',
      if (tunnelPort != null) 'tunnel_port=$tunnelPort',
      if (maxSize > 0) 'max_size=$maxSize',
      'video_bit_rate=$bitRate',
      if (audioBitRate != null) 'audio_bit_rate=$audioBitRate',
      if (maxFps > 0) 'max_fps=$maxFps',
      'tunnel_forward=false',
      if (angle != null) 'angle=$angle',
      if (screenOffTimeout != null) 'screen_off_timeout=$screenOffTimeout',
      if (captureOrientation != null) 'capture_orientation=$captureOrientation',
      if (captureOrientationLock != null)
        'capture_orientation_lock=$captureOrientationLock',
      'control=$control',
      if (displayId != null) 'display_id=$displayId',
      if (newDisplay != null) 'new_display=$newDisplay',
      if (displayImePolicy != null) 'display_ime_policy=$displayImePolicy',
      'audio=$audio',
      if (audioDup != null) 'audio_dup=$audioDup',
      if (showTouches != null) 'show_touches=$showTouches',      if (videoCodecOptions != null) 'video_codec_options=$videoCodecOptions',
      if (audioCodecOptions != null) 'audio_codec_options=$audioCodecOptions',
      if (videoEncoder != null) 'video_encoder=$videoEncoder',
      if (audioEncoder != null) 'audio_encoder=$audioEncoder',
      if (cameraId != null) 'camera_id=$cameraId',
      if (cameraSize != null) 'camera_size=$cameraSize',
      if (cameraAr != null) 'camera_ar=$cameraAr',
      if (cameraFps != null) 'camera_fps=$cameraFps',
      if (forceAdbForward != null) 'force_adb_forward=$forceAdbForward',
      if (powerOffOnClose != null) 'power_off_on_close=$powerOffOnClose',
      if (downsizeOnError != null) 'downsize_on_error=$downsizeOnError',
      if (tcpip != null) 'tcpip=$tcpip',
      if (tcpipDst != null) 'tcpip_dst=$tcpipDst',
      if (powerOn != null) 'power_on=$powerOn',
      if (killAdbOnClose != null) 'kill_adb_on_close=$killAdbOnClose',
      if (cameraHighSpeed != null) 'camera_high_speed=$cameraHighSpeed',
      if (vdDestroyContent != null) 'vd_destroy_content=$vdDestroyContent',
      if (vdSystemDecorations != null)
        'vd_system_decorations=$vdSystemDecorations',
      if (list != null) 'list=$list',
      'send_device_meta=true',
      'send_frame_meta=true',
      'send_codec_meta=true',
    ];
  }
}
